name: deploy:heroku

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - run: echo "version=${{ steps.package-version.outputs.current-version }} | sed -e 's/\./-/g'"

      - name: heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: "qa-flow-demo-${{ env.version }}"
      - run: heroku pipelines:add qa-flow-demo --app=qa-flow-demo-custom-${{ env.version }} --stage=staging
