name: deploy:heroku

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: "qa-flow-demo-custom-1-0-0"
      - run: heroku pipelines:add qa-flow-demo --app=qa-flow-demo-custom-1-0-0 --stage=staging
